# Generated by Django 4.2.1 on 2023-05-13 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_alter_team_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='제목')),
                ('content', models.TextField(blank=True, null=True, verbose_name='내용')),
                ('is_complete', models.BooleanField(default=False, verbose_name='완료 여부')),
                ('completed_date', models.DateTimeField(blank=True, null=True, verbose_name='완료일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일자')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='수정 일자')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_user', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_team', to='users.team', verbose_name='할당 팀')),
            ],
            options={
                'verbose_name_plural': '업무',
                'db_table': 'Task',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('subtask_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_complete', models.BooleanField(default=False, verbose_name='완료 여부')),
                ('completed_date', models.DateTimeField(blank=True, null=True, verbose_name='완료일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일자')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='수정 일자')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtask_task', to='task.task', verbose_name='상위 업무')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtask_user', to='users.team', verbose_name='할당 팀')),
            ],
            options={
                'verbose_name_plural': '하위 업무',
                'db_table': 'SubTask',
                'managed': True,
            },
        ),
    ]
