# Generated by Django 4.2.1 on 2023-05-14 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_team_table'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtask',
            old_name='task_id',
            new_name='task',
        ),
        migrations.AlterField(
            model_name='task',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_team', to='users.team', verbose_name='작성팀'),
        ),
    ]
