# Generated by Django 4.2.1 on 2023-05-14 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_rename_task_id_subtask_task_alter_task_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_id',
            new_name='id',
        ),
    ]
