# Generated by Django 4.2.1 on 2023-05-14 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_rename_task_id_task_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='id',
            new_name='task_id',
        ),
    ]
